//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignInfo
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", ConfigurationName="SignInfo.SignInfoService")]
    public interface SignInfoService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SignInfo.getSignInfosByKeySNResponse> getSignInfosByKeySNAsync(SignInfo.getSignInfosByKeySN request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SignInfo.getSigninfoBySignSNResponse> getSigninfoBySignSNAsync(SignInfo.getSigninfoBySignSN request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SignInfo.getSigninfosByUserCodeResponse> getSigninfosByUserCodeAsync(SignInfo.getSigninfosByUserCode request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SignInfo.addSignForWriteKeyResponse> addSignForWriteKeyAsync(SignInfo.addSignForWriteKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SignInfo.addSignInfoResponse> addSignInfoAsync(SignInfo.addSignInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SignInfo.delSignInfoBySignSNResponse> delSignInfoBySignSNAsync(SignInfo.delSignInfoBySignSN request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://signinfoServices.services.web.iSignatureServer.kg.com/")]
    public partial class signinfo
    {
        
        private string applyDateField;
        
        private string checkCodeField;
        
        private string extParam1Field;
        
        private string extParam2Field;
        
        private string gaclipdataField;
        
        private string gasignmetaField;
        
        private string gawritekeyField;
        
        private string gdcaEncodeDateField;
        
        private keyinfo keyinfoField;
        
        private string oldcheckcodeField;
        
        private orginfo orginfoField;
        
        private string overDateField;
        
        private string pfxCertDataField;
        
        private string pfxFileNameField;
        
        private string pfxPwdField;
        
        private string picMd5Field;
        
        private string signCheckField;
        
        private string signDataField;
        
        private string signDateField;
        
        private string signDescriptionField;
        
        private string signExtField;
        
        private string signHeightField;
        
        private string signIPField;
        
        private string signNameField;
        
        private string signSizeField;
        
        private string signSnField;
        
        private string signStatusField;
        
        private string signTypeField;
        
        private string signWidthField;
        
        private int tidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string applyDate
        {
            get
            {
                return this.applyDateField;
            }
            set
            {
                this.applyDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string checkCode
        {
            get
            {
                return this.checkCodeField;
            }
            set
            {
                this.checkCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string extParam1
        {
            get
            {
                return this.extParam1Field;
            }
            set
            {
                this.extParam1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string extParam2
        {
            get
            {
                return this.extParam2Field;
            }
            set
            {
                this.extParam2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string gaclipdata
        {
            get
            {
                return this.gaclipdataField;
            }
            set
            {
                this.gaclipdataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string gasignmeta
        {
            get
            {
                return this.gasignmetaField;
            }
            set
            {
                this.gasignmetaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string gawritekey
        {
            get
            {
                return this.gawritekeyField;
            }
            set
            {
                this.gawritekeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string gdcaEncodeDate
        {
            get
            {
                return this.gdcaEncodeDateField;
            }
            set
            {
                this.gdcaEncodeDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public keyinfo keyinfo
        {
            get
            {
                return this.keyinfoField;
            }
            set
            {
                this.keyinfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string oldcheckcode
        {
            get
            {
                return this.oldcheckcodeField;
            }
            set
            {
                this.oldcheckcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public orginfo orginfo
        {
            get
            {
                return this.orginfoField;
            }
            set
            {
                this.orginfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string overDate
        {
            get
            {
                return this.overDateField;
            }
            set
            {
                this.overDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string pfxCertData
        {
            get
            {
                return this.pfxCertDataField;
            }
            set
            {
                this.pfxCertDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string pfxFileName
        {
            get
            {
                return this.pfxFileNameField;
            }
            set
            {
                this.pfxFileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string pfxPwd
        {
            get
            {
                return this.pfxPwdField;
            }
            set
            {
                this.pfxPwdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string picMd5
        {
            get
            {
                return this.picMd5Field;
            }
            set
            {
                this.picMd5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string signCheck
        {
            get
            {
                return this.signCheckField;
            }
            set
            {
                this.signCheckField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string signData
        {
            get
            {
                return this.signDataField;
            }
            set
            {
                this.signDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string signDate
        {
            get
            {
                return this.signDateField;
            }
            set
            {
                this.signDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string signDescription
        {
            get
            {
                return this.signDescriptionField;
            }
            set
            {
                this.signDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string signExt
        {
            get
            {
                return this.signExtField;
            }
            set
            {
                this.signExtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string signHeight
        {
            get
            {
                return this.signHeightField;
            }
            set
            {
                this.signHeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string signIP
        {
            get
            {
                return this.signIPField;
            }
            set
            {
                this.signIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string signName
        {
            get
            {
                return this.signNameField;
            }
            set
            {
                this.signNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string signSize
        {
            get
            {
                return this.signSizeField;
            }
            set
            {
                this.signSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string signSn
        {
            get
            {
                return this.signSnField;
            }
            set
            {
                this.signSnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string signStatus
        {
            get
            {
                return this.signStatusField;
            }
            set
            {
                this.signStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string signType
        {
            get
            {
                return this.signTypeField;
            }
            set
            {
                this.signTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string signWidth
        {
            get
            {
                return this.signWidthField;
            }
            set
            {
                this.signWidthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public int tid
        {
            get
            {
                return this.tidField;
            }
            set
            {
                this.tidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://signinfoServices.services.web.iSignatureServer.kg.com/")]
    public partial class keyinfo
    {
        
        private string applyDateField;
        
        private string checkCodeField;
        
        private string descriptionField;
        
        private string ext1Field;
        
        private string ext2Field;
        
        private string gdcakeynameField;
        
        private string isManagerField;
        
        private string isVirtualField;
        
        private string keySnField;
        
        private string keyStatusField;
        
        private string keyUniqueMarkerField;
        
        private string logoutDateField;
        
        private string oldcheckcodeField;
        
        private string orgNameField;
        
        private orginfo orginfoField;
        
        private string overDateField;
        
        private string passwordField;
        
        private string pfxFileNameField;
        
        private string pfxPwdField;
        
        private string pfxcertdataField;
        
        private string phoneField;
        
        private int seqNumberField;
        
        private int signOfflineField;
        
        private string signOverDateField;
        
        private string thisnoField;
        
        private int tidField;
        
        private string userCodeField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string applyDate
        {
            get
            {
                return this.applyDateField;
            }
            set
            {
                this.applyDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string checkCode
        {
            get
            {
                return this.checkCodeField;
            }
            set
            {
                this.checkCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ext1
        {
            get
            {
                return this.ext1Field;
            }
            set
            {
                this.ext1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ext2
        {
            get
            {
                return this.ext2Field;
            }
            set
            {
                this.ext2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string gdcakeyname
        {
            get
            {
                return this.gdcakeynameField;
            }
            set
            {
                this.gdcakeynameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string isManager
        {
            get
            {
                return this.isManagerField;
            }
            set
            {
                this.isManagerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string isVirtual
        {
            get
            {
                return this.isVirtualField;
            }
            set
            {
                this.isVirtualField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string keySn
        {
            get
            {
                return this.keySnField;
            }
            set
            {
                this.keySnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string keyStatus
        {
            get
            {
                return this.keyStatusField;
            }
            set
            {
                this.keyStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string keyUniqueMarker
        {
            get
            {
                return this.keyUniqueMarkerField;
            }
            set
            {
                this.keyUniqueMarkerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string logoutDate
        {
            get
            {
                return this.logoutDateField;
            }
            set
            {
                this.logoutDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string oldcheckcode
        {
            get
            {
                return this.oldcheckcodeField;
            }
            set
            {
                this.oldcheckcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string orgName
        {
            get
            {
                return this.orgNameField;
            }
            set
            {
                this.orgNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public orginfo orginfo
        {
            get
            {
                return this.orginfoField;
            }
            set
            {
                this.orginfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string overDate
        {
            get
            {
                return this.overDateField;
            }
            set
            {
                this.overDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string pfxFileName
        {
            get
            {
                return this.pfxFileNameField;
            }
            set
            {
                this.pfxFileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string pfxPwd
        {
            get
            {
                return this.pfxPwdField;
            }
            set
            {
                this.pfxPwdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string pfxcertdata
        {
            get
            {
                return this.pfxcertdataField;
            }
            set
            {
                this.pfxcertdataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public int seqNumber
        {
            get
            {
                return this.seqNumberField;
            }
            set
            {
                this.seqNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public int signOffline
        {
            get
            {
                return this.signOfflineField;
            }
            set
            {
                this.signOfflineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string signOverDate
        {
            get
            {
                return this.signOverDateField;
            }
            set
            {
                this.signOverDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string thisno
        {
            get
            {
                return this.thisnoField;
            }
            set
            {
                this.thisnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public int tid
        {
            get
            {
                return this.tidField;
            }
            set
            {
                this.tidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string userCode
        {
            get
            {
                return this.userCodeField;
            }
            set
            {
                this.userCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://signinfoServices.services.web.iSignatureServer.kg.com/")]
    public partial class orginfo
    {
        
        private string orgCodeField;
        
        private string orgNameField;
        
        private string orgStatusField;
        
        private string orgfakeCodeField;
        
        private orginfo parentField;
        
        private string seqCodeField;
        
        private int seqNumberField;
        
        private int tidField;
        
        private string uniqueMarkerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string orgCode
        {
            get
            {
                return this.orgCodeField;
            }
            set
            {
                this.orgCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string orgName
        {
            get
            {
                return this.orgNameField;
            }
            set
            {
                this.orgNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string orgStatus
        {
            get
            {
                return this.orgStatusField;
            }
            set
            {
                this.orgStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string orgfakeCode
        {
            get
            {
                return this.orgfakeCodeField;
            }
            set
            {
                this.orgfakeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public orginfo parent
        {
            get
            {
                return this.parentField;
            }
            set
            {
                this.parentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string seqCode
        {
            get
            {
                return this.seqCodeField;
            }
            set
            {
                this.seqCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int seqNumber
        {
            get
            {
                return this.seqNumberField;
            }
            set
            {
                this.seqNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int tid
        {
            get
            {
                return this.tidField;
            }
            set
            {
                this.tidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string uniqueMarker
        {
            get
            {
                return this.uniqueMarkerField;
            }
            set
            {
                this.uniqueMarkerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSignInfosByKeySN", WrapperNamespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", IsWrapped=true)]
    public partial class getSignInfosByKeySN
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string keySn;
        
        public getSignInfosByKeySN()
        {
        }
        
        public getSignInfosByKeySN(string keySn)
        {
            this.keySn = keySn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSignInfosByKeySNResponse", WrapperNamespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", IsWrapped=true)]
    public partial class getSignInfosByKeySNResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("signInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SignInfo.signinfo[] signInfos;
        
        public getSignInfosByKeySNResponse()
        {
        }
        
        public getSignInfosByKeySNResponse(SignInfo.signinfo[] signInfos)
        {
            this.signInfos = signInfos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSigninfoBySignSN", WrapperNamespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", IsWrapped=true)]
    public partial class getSigninfoBySignSN
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signSn;
        
        public getSigninfoBySignSN()
        {
        }
        
        public getSigninfoBySignSN(string signSn)
        {
            this.signSn = signSn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSigninfoBySignSNResponse", WrapperNamespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", IsWrapped=true)]
    public partial class getSigninfoBySignSNResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SignInfo.signinfo signInfo;
        
        public getSigninfoBySignSNResponse()
        {
        }
        
        public getSigninfoBySignSNResponse(SignInfo.signinfo signInfo)
        {
            this.signInfo = signInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSigninfosByUserCode", WrapperNamespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", IsWrapped=true)]
    public partial class getSigninfosByUserCode
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userCode;
        
        public getSigninfosByUserCode()
        {
        }
        
        public getSigninfosByUserCode(string userCode)
        {
            this.userCode = userCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSigninfosByUserCodeResponse", WrapperNamespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", IsWrapped=true)]
    public partial class getSigninfosByUserCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("signInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SignInfo.signinfo[] signInfos;
        
        public getSigninfosByUserCodeResponse()
        {
        }
        
        public getSigninfosByUserCodeResponse(SignInfo.signinfo[] signInfos)
        {
            this.signInfos = signInfos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addSignForWriteKey", WrapperNamespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", IsWrapped=true)]
    public partial class addSignForWriteKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] image;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string imageExt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string keySN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string imageWidth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string imageHeight;
        
        public addSignForWriteKey()
        {
        }
        
        public addSignForWriteKey(byte[] image, string imageExt, string signName, string keySN, string imageWidth, string imageHeight)
        {
            this.image = image;
            this.imageExt = imageExt;
            this.signName = signName;
            this.keySN = keySN;
            this.imageWidth = imageWidth;
            this.imageHeight = imageHeight;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addSignForWriteKeyResponse", WrapperNamespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", IsWrapped=true)]
    public partial class addSignForWriteKeyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string result;
        
        public addSignForWriteKeyResponse()
        {
        }
        
        public addSignForWriteKeyResponse(string result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addSignInfo", WrapperNamespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", IsWrapped=true)]
    public partial class addSignInfo
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] image;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string imageExt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string keySN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string iamgeWidth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string imageHeight;
        
        public addSignInfo()
        {
        }
        
        public addSignInfo(byte[] image, string imageExt, string signName, string keySN, string iamgeWidth, string imageHeight)
        {
            this.image = image;
            this.imageExt = imageExt;
            this.signName = signName;
            this.keySN = keySN;
            this.iamgeWidth = iamgeWidth;
            this.imageHeight = imageHeight;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addSignInfoResponse", WrapperNamespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", IsWrapped=true)]
    public partial class addSignInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signsn;
        
        public addSignInfoResponse()
        {
        }
        
        public addSignInfoResponse(string signsn)
        {
            this.signsn = signsn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delSignInfoBySignSN", WrapperNamespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", IsWrapped=true)]
    public partial class delSignInfoBySignSN
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signSN;
        
        public delSignInfoBySignSN()
        {
        }
        
        public delSignInfoBySignSN(string signSN)
        {
            this.signSN = signSN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delSignInfoBySignSNResponse", WrapperNamespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", IsWrapped=true)]
    public partial class delSignInfoBySignSNResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://signinfoServices.services.web.iSignatureServer.kg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string result;
        
        public delSignInfoBySignSNResponse()
        {
        }
        
        public delSignInfoBySignSNResponse(string result)
        {
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface SignInfoServiceChannel : SignInfo.SignInfoService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SignInfoServiceClient : System.ServiceModel.ClientBase<SignInfo.SignInfoService>, SignInfo.SignInfoService
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SignInfoServiceClient() : 
                base(SignInfoServiceClient.GetDefaultBinding(), SignInfoServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SignInfoServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SignInfoServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SignInfoServiceClient.GetBindingForEndpoint(endpointConfiguration), SignInfoServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SignInfoServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SignInfoServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SignInfoServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SignInfoServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SignInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SignInfo.getSignInfosByKeySNResponse> SignInfo.SignInfoService.getSignInfosByKeySNAsync(SignInfo.getSignInfosByKeySN request)
        {
            return base.Channel.getSignInfosByKeySNAsync(request);
        }
        
        public System.Threading.Tasks.Task<SignInfo.getSignInfosByKeySNResponse> getSignInfosByKeySNAsync(string keySn)
        {
            SignInfo.getSignInfosByKeySN inValue = new SignInfo.getSignInfosByKeySN();
            inValue.keySn = keySn;
            return ((SignInfo.SignInfoService)(this)).getSignInfosByKeySNAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SignInfo.getSigninfoBySignSNResponse> SignInfo.SignInfoService.getSigninfoBySignSNAsync(SignInfo.getSigninfoBySignSN request)
        {
            return base.Channel.getSigninfoBySignSNAsync(request);
        }
        
        public System.Threading.Tasks.Task<SignInfo.getSigninfoBySignSNResponse> getSigninfoBySignSNAsync(string signSn)
        {
            SignInfo.getSigninfoBySignSN inValue = new SignInfo.getSigninfoBySignSN();
            inValue.signSn = signSn;
            return ((SignInfo.SignInfoService)(this)).getSigninfoBySignSNAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SignInfo.getSigninfosByUserCodeResponse> SignInfo.SignInfoService.getSigninfosByUserCodeAsync(SignInfo.getSigninfosByUserCode request)
        {
            return base.Channel.getSigninfosByUserCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SignInfo.getSigninfosByUserCodeResponse> getSigninfosByUserCodeAsync(string userCode)
        {
            SignInfo.getSigninfosByUserCode inValue = new SignInfo.getSigninfosByUserCode();
            inValue.userCode = userCode;
            return ((SignInfo.SignInfoService)(this)).getSigninfosByUserCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SignInfo.addSignForWriteKeyResponse> SignInfo.SignInfoService.addSignForWriteKeyAsync(SignInfo.addSignForWriteKey request)
        {
            return base.Channel.addSignForWriteKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<SignInfo.addSignForWriteKeyResponse> addSignForWriteKeyAsync(byte[] image, string imageExt, string signName, string keySN, string imageWidth, string imageHeight)
        {
            SignInfo.addSignForWriteKey inValue = new SignInfo.addSignForWriteKey();
            inValue.image = image;
            inValue.imageExt = imageExt;
            inValue.signName = signName;
            inValue.keySN = keySN;
            inValue.imageWidth = imageWidth;
            inValue.imageHeight = imageHeight;
            return ((SignInfo.SignInfoService)(this)).addSignForWriteKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SignInfo.addSignInfoResponse> SignInfo.SignInfoService.addSignInfoAsync(SignInfo.addSignInfo request)
        {
            return base.Channel.addSignInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SignInfo.addSignInfoResponse> addSignInfoAsync(byte[] image, string imageExt, string signName, string keySN, string iamgeWidth, string imageHeight)
        {
            SignInfo.addSignInfo inValue = new SignInfo.addSignInfo();
            inValue.image = image;
            inValue.imageExt = imageExt;
            inValue.signName = signName;
            inValue.keySN = keySN;
            inValue.iamgeWidth = iamgeWidth;
            inValue.imageHeight = imageHeight;
            return ((SignInfo.SignInfoService)(this)).addSignInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SignInfo.delSignInfoBySignSNResponse> SignInfo.SignInfoService.delSignInfoBySignSNAsync(SignInfo.delSignInfoBySignSN request)
        {
            return base.Channel.delSignInfoBySignSNAsync(request);
        }
        
        public System.Threading.Tasks.Task<SignInfo.delSignInfoBySignSNResponse> delSignInfoBySignSNAsync(string signSN)
        {
            SignInfo.delSignInfoBySignSN inValue = new SignInfo.delSignInfoBySignSN();
            inValue.signSN = signSN;
            return ((SignInfo.SignInfoService)(this)).delSignInfoBySignSNAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SignInfoServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SignInfoServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://220.165.143.90:8089/iSignatureServer/services/SignInfoService");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SignInfoServiceClient.GetBindingForEndpoint(EndpointConfiguration.SignInfoServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SignInfoServiceClient.GetEndpointAddress(EndpointConfiguration.SignInfoServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            SignInfoServicePort,
        }
    }
}
